import {
	siAngular,
	siBun,
	siCapacitor,
	siClaude,
	siDocker,
	siElectron,
	siEslint,
	siFirebase,
	siGit,
	siGithub,
	siGithubactions,
	siGithubcopilot,
	siGitlab,
	siIonic,
	siJest,
	siKotlin,
	siLinux,
	siMaterialdesign,
	siMinimax,
	siModelcontextprotocol,
	siMongodb,
	siMongoose,
	siNestjs,
	siNodedotjs,
	siNpm,
	siNx,
	siOpencode,
	siPrettier,
	siPrimeng,
	siPrisma,
	siReact,
	siReactivex,
	siSass,
	siStorybook,
	siTailwindcss,
	siTypescript,
	siVite,
	siVitest,
	siVuedotjs,
	siX,
	siZod,
} from 'simple-icons';
import type {
	Capability,
	HeroPanel,
	LanguageOption,
	Locale,
	PortfolioCopy,
	PlaygroundStepDefinition,
	PublicLink,
	Technology,
	Telemetry,
} from './portfolio.types';

export const PORTFOLIO_COPY: Readonly<Record<Locale, PortfolioCopy>> = {
	en: {
		navWork: 'Selected work',
		navLab: 'Frontend lab',
		navAbout: 'Approach',
		availability: 'Available for thoughtful product work',
		viewWork: 'View examples',
		contact: 'Start a conversation',
		role: 'Frontend engineer building operational web and mobile products.',
		intro: 'I combine product-focused frontend development with TypeScript architecture, testing and developer tooling.',
	},
	es: {
		navWork: 'Trabajo seleccionado',
		navLab: 'Laboratorio',
		navAbout: 'Enfoque',
		availability: 'Disponible para proyectos de producto',
		viewWork: 'Ver ejemplos',
		contact: 'Hablemos',
		role: 'Frontend engineer que construye productos web y móviles operacionales.',
		intro: 'Combino desarrollo frontend orientado a producto con arquitectura TypeScript, testing y tooling para developers.',
	},
};

export const PUBLIC_LINKS: readonly PublicLink[] = [
	{
		label: 'LinkedIn',
		href: 'https://www.linkedin.com/in/mario-cabrero-volarich',
		imageSrc: '/icons/linkedin-profile-badge.svg',
	},
	{
		label: 'GitHub',
		href: 'https://github.com/CartagoGit',
		iconPath: siGithub.path,
	},
	{
		label: 'npm',
		href: 'https://www.npmjs.com/~cartago-git',
		iconPath: siNpm.path,
		color: '#cb3837',
	},
	{
		label: 'MCP Vertex',
		href: 'https://github.com/CartagoGit/mcp-vertex',
		imageSrc: '/icons/mcp-vertex.svg',
	},
	{
		label: 'QuickModel',
		href: 'https://github.com/CartagoGit/quickmodel',
		imageSrc: '/icons/quickmodel.png',
	},
];

export const HERO_PANELS: readonly HeroPanel[] = [
	{
		id: 'overview',
		label: 'Angular',
		metric: 'UI',
		detail: 'Framework for structured, reactive web products with SSR and signals.',
		iconPath: siAngular.path,
		color: '#ff2d95',
		iconAsset: '/icons/angular.svg',
	},
	{
		id: 'workflows',
		label: 'TypeScript',
		metric: 'TS',
		detail: 'Typed contracts for interfaces, libraries and developer tooling.',
		iconPath: siTypescript.path,
		color: '#3178c6',
	},
	{
		id: 'quality',
		label: 'Vitest',
		metric: 'VT',
		detail: 'Fast unit and integration testing that keeps frontend behaviour dependable.',
		iconPath: siVitest.path,
		color: '#fcc72b',
	},
	{
		id: 'mobile',
		label: 'Ionic + Capacitor',
		metric: 'MOB',
		detail: 'A shared product system delivered to web and native mobile surfaces.',
		iconPath: siIonic.path || siCapacitor.path,
		color: '#3880ff',
	},
	{
		id: 'tooling',
		label: 'Bun',
		metric: 'BUN',
		detail: 'A fast JavaScript runtime and toolkit used to keep local feedback loops short.',
		iconPath: siBun.path,
		color: '#f9f1e8',
	},
	{
		id: 'delivery',
		label: 'Docker',
		metric: 'CTR',
		detail: 'Containerised delivery for reproducible environments and public image distribution.',
		iconPath: siDocker.path,
		color: '#2496ed',
	},
];

export const TECHNOLOGY_MARQUEE: readonly Technology[] = [
	{ label: 'TypeScript', iconPath: siTypescript.path, color: '#3178c6' },
	{ label: 'Angular', iconPath: siAngular.path, color: '#ff2d95' },
	{ label: 'RxJS', iconPath: siReactivex.path, color: '#b7178c' },
	{ label: 'Ionic', iconPath: siIonic.path, color: '#3880ff' },
	{ label: 'Capacitor', iconPath: siCapacitor.path, color: '#119eff' },
	{
		label: 'Angular Material',
		iconPath: siMaterialdesign.path,
		color: '#757575',
	},
	{ label: 'Sass', iconPath: siSass.path, color: '#cc6699' },
	{ label: 'Bun', iconPath: siBun.path, color: '#f9f1e1' },
	{ label: 'Node.js', iconPath: siNodedotjs.path, color: '#339933' },
	{ label: 'NestJS', iconPath: siNestjs.path, color: '#e0234e' },
	{ label: 'npm', iconPath: siNpm.path, color: '#cb3837' },
	{ label: 'Docker', iconPath: siDocker.path, color: '#2496ed' },
	{ label: 'Git', iconPath: siGit.path, color: '#f05032' },
	{ label: 'GitLab CI', iconPath: siGitlab.path, color: '#fc6d26' },
	{ label: 'Vitest', iconPath: siVitest.path, color: '#6e9f18' },
	{ label: 'Jest', iconPath: siJest.path, color: '#c21325' },
	{
		label: 'GitHub Actions',
		iconPath: siGithubactions.path,
		color: '#2088ff',
	},
	{ label: 'Vue', iconPath: siVuedotjs.path, color: '#4fc08d' },
	{ label: 'React', iconPath: siReact.path, color: '#61dafb' },
	{ label: 'Electron', iconPath: siElectron.path, color: '#47848f' },
	{ label: 'Tailwind CSS', iconPath: siTailwindcss.path, color: '#06b6d4' },
	{ label: 'PrimeNG', iconPath: siPrimeng.path, color: '#dd0031' },
	{ label: 'Storybook', iconPath: siStorybook.path, color: '#ff4785' },
	{ label: 'Vite', iconPath: siVite.path, color: '#646cff' },
	{ label: 'Nx', iconPath: siNx.path, color: '#143055' },
	{ label: 'MongoDB', iconPath: siMongodb.path, color: '#47a248' },
	{ label: 'Mongoose', iconPath: siMongoose.path, color: '#880000' },
	{ label: 'Prisma', iconPath: siPrisma.path, color: '#2d3748' },
	{ label: 'Zod', iconPath: siZod.path, color: '#3e67b1' },
	{ label: 'Firebase', iconPath: siFirebase.path, color: '#dd2c00' },
	{ label: 'Linux', iconPath: siLinux.path, color: '#fcc624' },
	{ label: 'Kotlin', iconPath: siKotlin.path, color: '#7f52ff' },
	{ label: 'Claude', iconPath: siClaude.path, color: '#d97757' },
	{ label: 'MiniMax', iconPath: siMinimax.path, color: '#e8e8e8' },
	{ label: 'Grok', iconPath: siX.path, color: '#e8e8e8' },
	{ label: 'OpenCode', iconPath: siOpencode.path, color: '#e8e8e8' },
	{
		label: 'GitHub Copilot',
		iconPath: siGithubcopilot.path,
		color: '#ffffff',
	},
	{
		label: 'Model Context Protocol',
		iconPath: siModelcontextprotocol.path,
		color: '#ffffff',
	},
	{ label: 'ESLint', iconPath: siEslint.path, color: '#4b32c3' },
	{ label: 'Prettier', iconPath: siPrettier.path, color: '#f7b93e' },
	{ label: 'GitHub', iconPath: siGithub.path, color: '#ffffff' },
];

export const LANGUAGES: readonly LanguageOption[] = [
	{ id: 'en', label: 'English', detail: 'US + UK' },
	{ id: 'es', label: 'Español', detail: 'España' },
];

export const CAPABILITIES: readonly Capability[] = [
	{
		id: 'product',
		eyebrow: '01 / Product interfaces',
		title: 'Operational by design.',
		detail: 'Interfaces for people who use them all day: dense information, clear next actions and graceful empty states.',
		tools: ['Angular', 'SCSS', 'Responsive UI'],
		proof: 'Workflow interfaces · complex forms · interaction design',
	},
	{
		id: 'architecture',
		eyebrow: '02 / Angular architecture',
		title: 'Explicitly reactive.',
		detail: 'Standalone components, signals and typed boundaries make state changes understandable, testable and fast.',
		tools: ['Angular 22', 'Signals', 'Zoneless'],
		proof: 'Zoneless Calculator · production Angular patterns',
	},
	{
		id: 'mobile',
		eyebrow: '03 / Mobile delivery',
		title: 'One product, more surfaces.',
		detail: 'Web workflows designed for touch, constrained space and release-ready Android delivery — not simply shrunk desktop screens.',
		tools: ['Ionic', 'Capacitor', 'Android'],
		proof: 'Web + Android operational delivery',
	},
	{
		id: 'quality',
		eyebrow: '04 / Testing & quality',
		title: 'Confidence is a feature.',
		detail: 'A focused testing pyramid, semantic HTML and performance budgets keep product work reliable as it grows.',
		tools: ['Vitest', 'Accessibility', 'Performance'],
		proof: 'Unit → integration → dependable releases',
	},
	{
		id: 'systems',
		eyebrow: '05 / Design systems',
		title: 'Consistent, not repetitive.',
		detail: 'Flexible primitives turn a visual language into reusable, accessible interfaces without flattening every screen into a template.',
		tools: ['Tokens', 'CDK', 'Storybook'],
		proof: 'Reusable UI patterns · states · responsive rules',
	},
	{
		id: 'tooling',
		eyebrow: '06 / Developer tooling',
		title: 'The frontend has an engine room.',
		detail: 'Typed contracts, CLIs and MCP tooling turn repeated engineering work into dependable workflows for teams and agents.',
		tools: ['TypeScript', 'MCP', 'Docker'],
		proof: 'MCP Vertex · QuickModel · Keyer',
	},
];

export const PLAYGROUND_STEPS: readonly PlaygroundStepDefinition[] = [
	{
		id: 'discover',
		label: 'Discover',
		hint: 'Understand the person and the workflow.',
	},
	{
		id: 'model',
		label: 'Model',
		hint: 'Make state and constraints explicit.',
	},
	{
		id: 'build',
		label: 'Build',
		hint: 'Compose a useful, responsive interface.',
	},
	{
		id: 'verify',
		label: 'Verify',
		hint: 'Test the journey before shipping.',
	},
];

export const TELEMETRY: readonly Telemetry[] = [
	{
		id: 'product',
		label: 'Product signal',
		title: 'A dashboard should reveal a decision.',
		value: '98%',
		valueLabel: 'workflow clarity',
		kpis: [
			['12', 'active patterns'],
			['4.2h', 'saved per flow'],
			['3', 'surfaces'],
		],
		bars: [34, 46, 42, 68, 61, 78, 88, 96],
		note: 'Signals are grouped by workflow, not by a vanity metric.',
	},
	{
		id: 'quality',
		label: 'Quality signal',
		title: 'Quality is a visible operating metric.',
		value: '94%',
		valueLabel: 'critical flow coverage',
		kpis: [
			['0', 'blocking a11y issues'],
			['18', 'checked states'],
			['1.8s', 'interaction budget'],
		],
		bars: [55, 58, 71, 67, 79, 85, 89, 94],
		note: 'Testing, semantics and performance share the same delivery conversation.',
	},
	{
		id: 'delivery',
		label: 'Delivery signal',
		title: 'One interface, more than one surface.',
		value: '2×',
		valueLabel: 'web + Android delivery',
		kpis: [
			['7', 'release checkpoints'],
			['3', 'deployment paths'],
			['99.9%', 'workflow availability'],
		],
		bars: [30, 38, 58, 55, 72, 69, 84, 91],
		note: 'Responsive product work considers the next device before it becomes a rewrite.',
	},
];
